[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[theme]
primaryColor = "#087f8c"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#e9f7f4"
textColor = "#17324d"
font = "sans serif"
